### ISSUE TITLE
Can't read bytes on an user-specific length

### ISSUE THREAD

**Issue by Gustavo6046** [lucastan/node-buffer-utils#1]
I want to read a string, given an encoding, but I want to specify the size, which is not given before the string's data.

Say I have the following:

    UFdBRA==

(or "PWAD")
As you can see, the size is not given before, like this:

    BFBXQUQ=

(or "\x04PWAD")
I'd like you to provide an optional argument to `BufferReader.readString` that can specify the size when it's not available in the data itself. Meanwhile I'll just resort to check the signature by using `r.readUInt32BE() === 1347895620`.

**Comment by lucastan** [comment]
added writeBytesRaw and readBytesRaw

so you can do readBytesRaw(size).toString(encoding)

**Comment by Gustavo6046** [comment]
Thank you. It was really something I was needing.

Meanwhile I'll use this:

```
writeChars = function(st, bw, cap, maxLen) {
  var c, data, i, len, padding, ref, results;
  if (cap == null) {
    cap = 0;
  }
  if (maxLen == null) {
    maxLen = st.toString('ascii').length;
  }
  if (cap > 0) {
    padding = "\x00".repeat(cap - st.length);
  } else {
    padding = "";
  }
  ref = st.slice(0, maxLen).toString() + padding;
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    c = ref[i];
    data = new Buffer(c, 'ascii');
    results.push(bw.writeUInt8(data.readUInt8()));
  }
  return results;
};
```
